apiVersion: v1
kind: Service
metadata:
  name: vprocache01       # name of the memcached.active.host in application.properties file
spec:
  type: ClusterIP
  selector:
    app: vprocache01
  ports:
  - port: 11211
    targetPort: memc-port
    protocol: TCP
