apiVersion: v1
kind: Service
metadata:
  name: vpromq01            # name of the rabbitmq.address in application.properties file
spec:
  type: ClusterIP
  selector:
    app: vpromq01
  ports:
  - port: 15672
    targetPort: rmq-port
    protocol: TCP
